name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Set AWS credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=your-aws-region" >> $GITHUB_ENV

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform changes
      run: terraform plan -out=tfplan

    # Add a prompt to ask the user whether to apply or destroy changes
    - name: Ask for action
      run: |
        read -p "Do you want to apply or destroy Terraform changes? (apply/destroy): " action
        echo "ACTION=$action" >> $GITHUB_ENV

    # Conditionally apply or destroy based on user input
    - name: Apply or destroy Terraform changes
      run: |
        if [ "$ACTION" = "apply" ]; then
          terraform apply tfplan -auto-approve
        elif [ "$ACTION" = "destroy" ]; then
          terraform destroy -auto-approve
        else
          echo "Invalid action. Exiting..."
          exit 1
        fi

    - name: Clean up
      run: rm tfplan
